<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class product extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // thức ăn cho chó
        DB::table('product')->insert([
            [
                'id' => '01',
                'name' => 'Product 1',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 2',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 2,
                'min_price' => 150,
                'max_price' => 250,
                'discount_price' => 200,
                'inventory' => 30,
                'image' => 'product2.jpg',
                'rating' => 4.0,
                'bestseller' => 0,
                'new' => 0,
                'number_of_sale' => 150,
                'size' => 'Medium',
                'gallery' => '["image3.jpg", "image4.jpg"]',
                'pet' => 'Mèo',
                'description' => 'Description for product 2',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            //thức ăn cho mèo
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Thức ăn',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            //
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => '',
                'name' => 'Product 1',
                'typeProduct_name' => 'Type 1',
                'typeProduct_id' => 1,
                'min_price' => 100,
                'max_price' => 200,
                'discount_price' => 150,
                'inventory' => 50,
                'image' => 'product1.jpg',
                'rating' => 4.5,
                'bestseller' => 1,
                'new' => 1,
                'number_of_sale' => 100,
                'size' => 'Large',
                'gallery' => '["image1.jpg", "image2.jpg"]',
                'pet' => 'Chó',
                'description' => 'Description for product 1',
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],

        ]);
    }
}
