<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class users extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'id' => 1,
                'name' => 'Nguyễnn Văn Lanh',
                'code' => '',
                'email' => 'nguyenvanlanh@gmail.com',
                'phone' => '0353456788',
                'date_of_birth' => '1990-01-01',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('01011990'),
                'date_join' => '2024-01-02',
                'remember_token' => '010122',
                'password_reset_token' => '19900101',
                'created_at' => '2024-05-20 10:25:27',
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Trần Thị Bé',
                'code' => '',
                'email' => 'tranbe@gmail.com',
                'phone' => '0353456788',
                'date_of_birth' => '1991-02-02',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('02021991'),
                'date_join' => '2023-03-02',
                'remember_token' => '020224',
                'password_reset_token' => '19910202',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Lê Văn Chinh',
                'code' => '',
                'email' => 'lechinh@gmail.com',
                'phone' => '0373456787',
                'date_of_birth' => '1992-03-03',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('03031992'),
                'date_join' => '2024-07-02',
                'remember_token' => '030324',
                'password_reset_token' => '19920303',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Phạm Thị Dung',
                'code' => '',
                'email' => 'phamthidung@gmail.com',
                'phone' => '0363456786',
                'date_of_birth' => '1993-04-04',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('04041993'),
                'date_join' => '2020-02-02',
                'remember_token' => '040424',
                'password_reset_token' => '19930404',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Vũ Văn Thịnh',
                'code' => '',
                'email' => 'vuvanthinh@gmail.com',
                'phone' => '0373456785',
                'date_of_birth' => '1994-05-05',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('05051994'),
                'date_join' => '2021-01-02',
                'remember_token' => '050524',
                'password_reset_token' => '19940505',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Đặng Thị Phương Tuyền',
                'code' => '',
                'email' => 'dtphuongtuyen@gmail.com',
                'phone' => '0333456784',
                'date_of_birth' => '1995-06-06',
                'role' => 'Sale Staff',
                'total' => 0,
                'password' => bcrypt('06061995'),
                'date_join' => '2024-01-02',
                'remember_token' => '060624',
                'password_reset_token' => '19950606',
                'created_at' => null,
                'updated_at' => '2024-05-20 10:37:46',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Bùi Văn Khánh',
                'code' => '',
                'email' => 'buivankhanh@gmail.com',
                'phone' => '0863456783',
                'date_of_birth' => '1996-07-07',
                'role' => 'Sale Staff',
                'total' => 0,
                'password' => bcrypt('07071996'),
                'date_join' => '2020-01-01',
                'remember_token' => '070724',
                'password_reset_token' => '19960707',
                'created_at' => null,
                'updated_at' => '2024-05-20 10:37:56',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Ngô Thị Tuyết',
                'code' => '',
                'email' => 'ngothituyet@gmail.com',
                'phone' => '0973456782',
                'date_of_birth' => '1997-08-08',
                'role' => 'Manager',
                'total' => 0,
                'password' => bcrypt('08081997'),
                'date_join' => '2018-01-02',
                'remember_token' => '080824',
                'password_reset_token' => '19970808',
                'created_at' => null,
                'updated_at' => '2024-05-20 10:29:23',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Hoàng Văn Thám',
                'code' => '',
                'email' => 'hoangvantham@gmail.com',
                'phone' => '0933456781',
                'date_of_birth' => '1998-09-09',
                'role' => 'Service Staff',
                'total' => 0,
                'password' => bcrypt('09091998'),
                'date_join' => '2021-07-02',
                'remember_token' => '090924',
                'password_reset_token' => '19980909',
                'created_at' => null,
                'updated_at' => '2024-05-20 10:38:09',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Dương Thị Linh',
                'code' => '',
                'email' => 'duongthilinh@gmal.com',
                'phone' => '0383456780',
                'date_of_birth' => '1999-10-10',
                'role' => 'Customer',
                'total' => 0,
                'password' => bcrypt('10101999'),
                'date_join' => '2024-01-02',
                'remember_token' => '101024',
                'password_reset_token' => '19991010',
                'created_at' => null,
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Nguyễn Dung',
                'code' => 'EMP82448',
                'email' => 'dungnguyen19724@gmail.com',
                'phone' => '0942154529',
                'date_of_birth' => null,
                'role' => 'Admin',
                'total' => 0,
                'password' => null,
                'date_join' => '2024-05-22',
                'remember_token' => null,
                'password_reset_token' => null,
                'created_at' => '2024-05-20 10:25:47',
                'updated_at' => '2024-05-20 10:29:42',
                'deleted_at' => null,
            ],
        ]);
    }
}
